fix: switch to use maintained ruby/setup-ruby
Gihub actions/runs log:

Run actions/setup-ruby@v1
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.6.x not found

Signed-off-by: Amos Kong <kongjianjun@gmail.com>